---
title: "02_full_monotonic_model"
format: html
editor: visual
---

```{r setup}
#| label: setup
#| include: FALSE

if (!require("pacman")) install.packages("pacman")
pacman::p_load(brms, ggplot2, patchwork, plotly, tidybayes, modelr, viridis, tidyverse, dplyr, truncnorm, lme4, faux, scam, bayestestR, faux)

# Set the current working directory to the one where this file is
current_working_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(current_working_dir)

# options to increase efficiency of brms models (optional)
options(brms.backend = "cmdstanr")
options(mc.cores = parallel::detectCores())

```

# Data & Wrangling

Wrangle the data, generate derivatives for the analysis.

```{r}
#| label: data_wrangling

# load in data 2025/09/11
xdata <- read_csv("../data/merged_250911.csv")

# derive some relevant measurements
xdata <- xdata |> 
  # remove erroneous data points
  filter(delta_t != 0) |> 
  # derive derivates
  mutate(
         # make delta_f positive / negative
         delta_f_raw = ifelse(stimuli_direction == "p", delta_f, delta_f * -1),
         # centralise
         delta_f_raw_c = delta_f_raw - mean(delta_f_raw),
         # transform delta_f_raw Hz into STs (reference 150Hz)
         delta_f_raw_st = 12 * log2((150-delta_f_raw)/150),
         # transform response_f relative to baseline 150hz      
         response_f_rel = response_f - 150,
         # transform response_f into STs (reference 150Hz)
         response_f_rel_st = 12 * log2((150-response_f_rel)/150),
         # adjust response direction for absolute delta_f values
         response_f_rel_sign = ifelse(delta_f_raw > 0, response_f_rel, -response_f_rel),
         # transform response_f_rel_sign into STs (reference 150Hz)
         response_f_rel_sign_st = 12 * log2((150-response_f_rel_sign)/150),
         # calculate response proportional to delta_f
         response_f_prop = response_f_rel / delta_f_raw,
         # calculate response proportional to delta_f in STs
         response_f_prop_st = response_f_rel_st / delta_f_raw_st,
         # make participant ID a character vector
         participant = as.character(participant)
         )

```

# Exploration of landscape
## 2D
We explore how pitch perception changes as a function of `delta_t` and `delta_f.`

```{r}
#| label: descriptive_exploration

xdata_agg <- xdata |> 
  group_by(delta_f_raw, delta_t, participant) |> 
  summarise(response_f_rel = mean(response_f_rel, na.rm = TRUE))
  
xdata_agg_all <- xdata |> 
  group_by(delta_f_raw, delta_t) |> 
  summarise(response_f_rel = mean(response_f_rel, na.rm = TRUE))
  
descriptive_plot <- 
ggplot(data = xdata_agg, 
       aes(x = delta_t,
           y = response_f_rel,
           color = delta_f_raw)) +
  geom_point(data = xdata_agg_all) +
  geom_line(data = xdata_agg_all,
             aes(group = delta_f_raw),
             lwd = 2.5,
            color = "black") +
  geom_line(data = xdata_agg_all,
             aes(group = delta_f_raw),
             lwd = 2) +
  # scale_y_continuous(limits = c(-20,20),
  #                    breaks = seq(-20,20,10)) +
  scale_x_continuous(breaks = c(unique(xdata$delta_t))) +
  scale_color_viridis_c(option= "viridis") +
  geom_hline(yintercept = 0.25,
             lty = "dashed") +
  #scale_color_stepsn(colours = "viridis") +
  labs(x = "\nslope duration in ms",
       y = "average observed pitch response in Hz\n",
       color = "pitch difference") +
  theme_minimal()
  
descriptive_plot

```

## 3D

Slight non-linear relationship with delta_t. Let's look at it in 3-dimensional space:

```{r}
#| label: descriptive_exploration_2

# set up matrix
z_matrix <- matrix(xdata_agg_all$response_f_rel_st, nrow = 8, ncol = 6, byrow = TRUE)

x_axis <- unique(xdata_agg_all$delta_t)
y_axis <- unique(xdata_agg_all$delta_f_raw_st)

plot_ly(x = ~x_axis, y = ~y_axis, z = ~z_matrix, 
        type = "surface",
        colors = 'RdPu') |> 
  layout( scene = list(
    xaxis = list(title = 'Onset Duration (ms)', tickvals = x_axis, ticktext = x_axis),
    yaxis = list(title = 'Onset Frequency in STs', tickvals = list(-5,-4,-3,-2,-1,0,1,2,3,4,5), ticktext = list(-5,-4,-3,-2,-1,0,1,2,3,4,5)),
    zaxis = list(title = 'Response STs')
  ))

```

# Modelling
## Linear model
```{r}

# contrast code

# brms formula (full)
formula_linear = bf(response_f_rel ~ delta_t * delta_f_raw + (delta_t * delta_f_raw | participant), nu = 4)


# my priors 
mypriors <- c(
              prior(cauchy(0, 1), class = "b"),
              prior(cauchy(0, 10), class = "Intercept", lb = -45, ub = 45),
              prior(cauchy(0, 5), class = "sd", lb = 0),
              prior(lkj(1), class = "cor")
              )

# Run model with
linear_model <- brm(
  formula_linear,
  data = xdata,
  file = "../models/linear_model",
  family = student,
  #family = gaussian,
  seed = 123,
  iter = 4000,
  warmup = 2000,
  prior = mypriors, 
  control = list(adapt_delta = 0.95,
                 max_treedepth = 12)
  )

# check caterpillar
plot(linear_model) # mixes well

# check samples against data
pp_check(linear_model, ndraws = 100, type = "dens_overlay") + xlim(-50,50)

# "issue" with discrete responses. however we do not expect this to bias estimates
# to keep models computationally feasible, we refrain from using discrete version of the student-t regression

```

## Monotonic predictors

```{r}

# code predictors as ordered factors
xdata$delta_f_raw_o <- factor(xdata$delta_f_raw, 
                              levels = c(-40,-30,-20,-10,10,20,30,40),
                              ordered = TRUE)
xdata$delta_t_o <- factor(xdata$delta_t, 
                          levels = c(40,60,80,100,120,250),
                          ordered = TRUE)

# brms formula (full)
formula_mono = bf(response_f_rel ~ mo(delta_f_raw_o) * mo(delta_t_o) + (mo(delta_f_raw_o) * mo(delta_t_o) | participant), nu = 4)

# get priors
get_prior(formula_mono, xdata)

# my priors 
mypriors <- c(
              prior(cauchy(0, 10), class = "b"),
              prior(cauchy(0, 10), class = "Intercept"),
              prior(cauchy(0, 10), class = "sd", lb = 0),
              prior(lkj(1), class = "cor")
              )

# Run model with gaussian error term
mono_model <- brm(
  formula_mono,
  data = xdata,
  file = "../models/mono_model",
  family = student,
  seed = 123,
  iter = 4000,
  warmup = 2000,
  prior = mypriors, 
  control = list(adapt_delta = 0.99,
                 max_treedepth = 12)
  )

# check caterpillar
plot(mono_model) # mixes well

# check samples against data
pp_check(mono_model, ndraws = 100, type = "dens_overlay") 
# "issue" with discrete responses as well as "spikyness", which could technically be fixed by student error term?

```

# GAMs

```{r}

# make interaction term?

# brms formula (full)

# get priors

# my priors 
mypriors <- c(
              prior(cauchy(0, 10), class = "b"),
              prior(cauchy(0, 10), class = "Intercept"),
              prior(cauchy(0, 10), class = "sd", lb = 0),
              prior(lkj(1), class = "cor")
              )

# Run model with gaussian error term
gam_model <- brm(
  formula_gam,
  data = xdata,
  file = "../models/gam_model",
  family = student,
  seed = 123,
  iter = 4000,
  warmup = 2000,
  prior = mypriors, 
  control = list(adapt_delta = 0.99,
                 max_treedepth = 12)
  )

# check caterpillar
plot(gam_model) # mixes well

# check samples against data
pp_check(gam_model, ndraws = 100, type = "dens_overlay") 
# "issue" with discrete responses as well as "spikyness", which could technically be fixed by student error term?

```



## Plot model

```{r}

#xdata$preds <- posterior_summary(posterior_epred(mono_model_d_f0))[,1]

# create new data for prediction
newdata <- expand_grid(delta_t_o = unique(xdata$delta_t_o),
                       delta_f_raw_o = unique(xdata$delta_f_raw_o)
                       )

# Visualize
prediction_mono <- mono_model |> 
  epred_draws(newdata = newdata,
              re_formula = NA) |> 
    group_by(delta_t_o, delta_f_raw_o) |> 
    summarise(pred_m = mean(.epred, na.rm = TRUE),
              pred_0025 = quantile(.epred, prob = 0.025),
              pred_0975 = quantile(.epred, prob = 0.975)) |> 
  rename(delta_t = delta_t_o,
         delta_f_raw = delta_f_raw_o) |> 
  mutate(delta_t = as.numeric(as.character(delta_t)),
         delta_f_raw = as.numeric(as.character(delta_f_raw)))

model_plot <- prediction_mono |> 
  ggplot(aes(x = delta_t,
             y = pred_m,
             color = delta_f_raw,
             group = delta_f_raw)) +
  geom_point() +
  geom_line(lwd = 2.5, 
             color = "black") +
  geom_line(lwd = 2) +
  scale_x_continuous(breaks = c(40,60,80,100,120,250)) +
  scale_color_viridis(option= "viridis") +
  labs(x = "\nslope duration in ms",
       y = "predicted response in Hz\n",
       color = "pitch difference") +
  theme_minimal()
  
model_plot

data_v_model <- descriptive_plot / model_plot +
  plot_layout(guides = 'collect',
              axes = 'collect')

data_v_model

```
